/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.Koneksi;
import database.SetTabel;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class SatuanBarang extends javax.swing.JInternalFrame {
    
    ResultSet resultSet;
    Koneksi connection;
    
    /**
     * Creates new form SatuanBarang
     */
    public SatuanBarang() {
        connection = new Koneksi();
        initComponents();
        getTable();
    }
    
    private void getTable(){
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID");
        model.addColumn("Nama Satuan");
        
        String[] namaKolom = {"No_id","Nama_Satuan"};
        String nameTable = "satuanbarang";
        
        try{
            
            int no = 1;
            resultSet = connection.querySellect(namaKolom, nameTable);
            
            while(resultSet.next()){
                model.addRow(new Object[]{
                    no++,
                    resultSet.getString(1),
                    resultSet.getString(2)
                });
            }
            
            connection.closeDatabase();
            tblSatuanBarang.setModel(model);
        }catch(SQLException e){
            System.out.println("Error try to populate table : " + e.getMessage());
        }
    }
    
    private void refreshAll(){
        tfNama.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSatuanBarang = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDellete = new javax.swing.JButton();

        jLabel1.setText("Menu Satuan Produk");

        jLabel2.setText("Nama Satuan");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblSatuanBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tblSatuanBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSatuanBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSatuanBarang);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDellete.setText("Dellete");
        btnDellete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnDellete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDellete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        String namaSatuan = tfNama.getText();
        
        if(namaSatuan.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama Satuan tidak boleh kosong");
        }else{
            String[] column = {"Nama_Satuan"};
            String[] value = {namaSatuan};
            String nameTable = "satuanbarang";
            
            connection.queryInsert(nameTable, column, value);
            connection.closeDatabase();
            
            getTable();
            refreshAll();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        
        String namaSatuan = tfNama.getText();
        
        if(namaSatuan.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama Satuan tidak boleh kosong");
        }else{
            
            int baris = tblSatuanBarang.getSelectedRow();
            int kolom = 1;
            
            String id = String.valueOf(tblSatuanBarang.getValueAt(baris, kolom));
            String[] column = {"Nama_Satuan"};
            String[] value = {namaSatuan};
            String nameTable = "satuanbarang";
            String condition = "No_id = " + id;
            
            connection.queryUppdate(nameTable, column, value, condition);
            connection.closeDatabase();
            
            getTable();
            refreshAll();
        }
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDelleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelleteActionPerformed
        
        int baris = tblSatuanBarang.getSelectedRow();
        int kolom = 1;
        String id = String.valueOf(tblSatuanBarang.getValueAt(baris, kolom));
        
         boolean confirmation = JOptionPane.showConfirmDialog(
                this,
                "Apakah anda yakin ingin menghapus data ini",
                "Peringatan!!!",
                JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION;
         
         if(confirmation){
             
            String nameTable = "satuanbarang";
            String condition = "No_id = " + id;
            
            connection.queryDelete(nameTable, condition);
            connection.closeDatabase();
         }else{
             return;
         }
         
        getTable();
        refreshAll();
    }//GEN-LAST:event_btnDelleteActionPerformed

    private void tblSatuanBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSatuanBarangMouseClicked
       
        int baris = tblSatuanBarang.getSelectedRow();
        
        String namaSatuan = String.valueOf(tblSatuanBarang.getValueAt(baris, 2));
        
        tfNama.setText(namaSatuan);
    }//GEN-LAST:event_tblSatuanBarangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDellete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSatuanBarang;
    private javax.swing.JTextField tfNama;
    // End of variables declaration//GEN-END:variables
}
